import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
const err=(e:unknown)=>NextResponse.json({error:e instanceof Error?e.message:"Unexpected server error."},{status:500});
const id=(v:unknown)=>Number(v);
export async function GET(){try{return NextResponse.json({data:await prisma.posMachine.findMany({orderBy:{id:"asc"}})})}catch(e){return err(e)}}
export async function POST(req:Request){try{const b=await req.json(); const stationId=id(b.station_id); if(!b.serial_number?.trim()||!b.version?.trim()||!b.type||!stationId)return NextResponse.json({error:"Serial number, version, type, and station are required."},{status:400}); return NextResponse.json({data:await prisma.posMachine.create({data:{serial_number:b.serial_number.trim(),version:b.version.trim(),type:b.type,station_id:stationId}})})}catch(e){if(typeof e === "object" && e !== null && "code" in e && e.code==="P2003")return NextResponse.json({error:"Selected station does not exist."},{status:400}); return err(e)}}
export async function PATCH(req:Request){try{const b=await req.json(); const machineId=id(b.id), stationId=id(b.station_id); if(!machineId||!b.serial_number?.trim()||!b.version?.trim()||!b.type||!stationId)return NextResponse.json({error:"POS id, serial number, version, type, and station are required."},{status:400}); return NextResponse.json({data:await prisma.posMachine.update({where:{id:machineId},data:{serial_number:b.serial_number.trim(),version:b.version.trim(),type:b.type,station_id:stationId}})})}catch(e){if(typeof e === "object" && e !== null && "code" in e && e.code==="P2025")return NextResponse.json({error:"POS machine not found."},{status:404}); if(typeof e === "object" && e !== null && "code" in e && e.code==="P2003")return NextResponse.json({error:"Selected station does not exist."},{status:400}); return err(e)}}
export async function DELETE(req:Request){try{const machineId=id((await req.json()).id); if(!machineId)return NextResponse.json({error:"POS id is required."},{status:400}); await prisma.posMachine.delete({where:{id:machineId}}); return NextResponse.json({data:true})}catch(e){if(typeof e === "object" && e !== null && "code" in e && e.code==="P2025")return NextResponse.json({error:"POS machine not found."},{status:404}); return err(e)}}
